### ISSUE TITLE
Multiple files downloading

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1302]
If you select multiple files and click download, it says 'Unknown command'. Is there any way to disable the button 'Download'/context menu 'Download' in case of multiple file selection? Thank you!

**Comment by nao-pon** [comment]
@svetlanadzhura Probably this problem was fixed @7a4d8202e8ba16c3c4d54d5297f977d5629d8463. Please try check on nightly build.

**Comment by paulcanning** [comment]
When I selected two files and download, it attempts to make a ZIP file, finishes and then does nothing. No ZIP file is in the folder or downloaded?

**Comment by nao-pon** [comment]
@paulcanning Your problem seems to be another problem with this.　Please make new issue. Thanks.

**Comment by svetlanadzhura** [comment]
@nao-pon The change  @ 7a4d820 is already in my code, but It seems it does not solve the problem

**Comment by nao-pon** [comment]
@svetlanadzhura Can you show me your connector configuration?

**Comment by svetlanadzhura** [comment]
I use mvc controller. Zipdl is in list of disabled commands:

Option.cs (20)
`        private static string[] _disabled = new string[] { "extract", "create", "zipdl" };`

So download is disabled for folders in root directory, but not disabled for file multiple selection.

And just in case connector configuration:
`driver.AddRoot(new Root(new DirectoryInfo(@volumePath + folder))
                        {
                            Alias = "Home", 
                            MaxUploadSizeInMb = 3,
                            MaxRootSizeInMb = 50,
                            IsLocked = IdentityService.IsReviewer  && ModelService.CurrentReport.Lock,
                            IsReadOnly = IdentityService.IsReviewer && ModelService.CurrentReport.Lock,
                            StartPath = new DirectoryInfo(@volumePath + folder + "/TestFolder"),
                            UploadAllow = new List<string> { "jpg", "xlsx", "xls", "doc", "docx", "pdf", "png", "tif", "tiff", "jpeg", "txt", "bmp"}
                        });`

**Comment by nao-pon** [comment]
@svetlanadzhura I checked with connector root option ``'disabled' => ['extract', 'create', 'zipdl'], That is no problem. Please check in elFinder latest nightly as standalone.

**Comment by paulcanning** [comment]
@nao-pon pretty sure I'm having the same problem. Selected two text files (from local file system root volume) and tried to download. The zip dialog shows, but then it disappears and then nothing happens after. No zip is made. Same issue. Using the nightly code.

**Comment by nao-pon** [comment]
@paulcanning In first post in this issue.
> If you select multiple files and click download, it says 'Unknown command'.

Are you seen 'Unknown command' dialog?

**Comment by paulcanning** [comment]
@nao-pon no, I'm not seeing any error. Do you really want a new issue where it's 99% the same as this one?

**Comment by nao-pon** [comment]
@paulcanning Yes, your case is a problem in zipdl command. Please attach a server response of zipdl command when creating new issue.

**Comment by nao-pon** [comment]
@svetlanadzhura  Today elFinder 2.1.10 released. Please check with 2.1.10. Thanks.

**Comment by svetlanadzhura** [comment]
I just tried 2.10.0. Now It allows to download multiple files (in my case without making of zip, that is fine for me). So now no error message and multiple download is working fine. Another problem I mentioned in ticket #1278 has been fixed as well. Great work, mate! Thanks!

**Comment by nao-pon** [comment]
@svetlanadzhura Thanks! :+1:
